ci:
  autoupdate_schedule: quarterly
repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt
        language: system
        types: [rust]
        args: ["--all", "--"]
      - id: cargo-check
        name: cargo check
        entry: cargo check
        language: system
        types: [rust]
        args: ["--workspace"]
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy
        language: system
        types: [rust]
        # https://doc.rust-lang.org/stable/clippy/
        args: [
          "--workspace",
          "--",
          "-Dwarnings",
          "-Dclippy::pedantic",
          "-Dclippy::nursery",
          "-Dclippy::cargo",
          # "Expect many false positives" https://rust-lang.github.io/rust-clippy/master/index.html#must_use_candidate
          "-Aclippy::must_use_candidate",
          # "It’s not bad at all." https://rust-lang.github.io/rust-clippy/master/index.html#cast_precision_loss
          "-Aclippy::cast-precision-loss",
          # Indicators::run() is long.
          "-Aclippy::too-many-lines",
          # https://github.com/seanmonstar/num_cpus/pull/128
          # https://github.com/seanmonstar/pretty-env-logger/pull/49
          # https://github.com/eminence/terminal-size/pull/49
          "-Aclippy::multiple-crate-versions",
        ]
        pass_filenames: false
