[package]
name = "libocdscardinal"
version = "0.1.0"
edition = "2021"
description = "Measures red flags and procurement indicators using OCDS data."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
