[package]
name = "libocdscardinal"
version = "0.1.0"
authors = ["Open Contracting Partnership <data@open-contracting.org>"]
edition = "2021"
description = "Measures red flags and procurement indicators using OCDS data."
repository = "http://github.com/open-contracting/cardinal-lib"
license = "MIT"
build = "build.rs"
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
crossbeam = "0.8"
log = "0.4"
num_cpus = "1.0"
pretty_env_logger = "0.4"
serde = "1.0"
serde_json = "1.0"

[build-dependencies]
glob = "0.3"

[dev-dependencies]
pretty_assertions = "1.0"
