name: Lint
on: [push, pull_request]
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          # Need feature(stdsimd) until config-rs can be upgraded.
          # https://github.com/mehcode/config-rs/issues/531
          # https://github.com/rust-lang/rust/issues/27731#event-11707724027
          toolchain: nightly-2024-01-01
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}
      - id: changed-files
        uses: tj-actions/changed-files@v44
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: cargo-check --files ${{ steps.changed-files.outputs.all_changed_files }}
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: cargo-clippy --files ${{ steps.changed-files.outputs.all_changed_files }}
      - uses: taiki-e/install-action@cargo-udeps
      - run: cargo udeps
